// Audits emoji coverage of a ~1000-item grocery list. For each item it reports
// whether it resolved via the curated table, the semantic embedding fallback, or
// the basket default. Run (from repo root):
//   swiftc Sources/Services/EmojiTable.swift Sources/Services/SemanticEmoji.swift \
//          Sources/Services/Emoji.swift tools/audit_coverage.swift -o /tmp/audit && /tmp/audit
import Foundation

let RAW = """
Potato, Carrot, Onion, Garlic, Broccoli, Cauliflower, Cabbage, Spinach, Kale, Lettuce, Cucumber, Tomato, Bell pepper, Zucchini, Eggplant, Mushroom, Celery, Asparagus, Green beans, Peas, Sweet potato, Butternut squash, Pumpkin, Radish, Turnip, Parsnip, Beetroot, Leek, Spring onion, Brussels sprout, Artichoke, Fennel, Swiss chard, Bok choy, Watercress, Rocket, Endive, Radicchio, Kohlrabi, Rutabaga, Okra, Sweet corn, Shallot, Ginger, Turmeric root, Horseradish, Daikon, Celeriac, Snow peas, Sugar snap peas, Broad beans, Edamame, Runner beans, Mange tout, Cherry tomato, Plum tomato, Beef tomato, White onion, Red onion, Spanish onion, Savoy cabbage, Red cabbage, White cabbage, Napa cabbage, Collard greens, Mustard greens, Dandelion greens, Iceberg lettuce, Romaine lettuce, Butterhead lettuce, Lollo Rosso, Oak leaf lettuce, Baby spinach, Portobello mushroom, Button mushroom, Chestnut mushroom, Shiitake mushroom, Oyster mushroom, Enoki mushroom, King oyster mushroom, Green pepper, Red pepper, Yellow pepper, Orange pepper, Jalapeno, Habanero, Birds eye chili, Scotch bonnet, Anaheim pepper, Poblano, Padron pepper, Shishito pepper, Spaghetti squash, Acorn squash, Pattypan squash, Chive, Lemongrass, Galangal, Bamboo shoot, Water chestnut.
Apple, Banana, Orange, Pear, Grape, Strawberry, Blueberry, Raspberry, Blackberry, Lemon, Lime, Grapefruit, Peach, Plum, Nectarine, Apricot, Cherry, Watermelon, Cantaloupe, Honeydew, Pineapple, Mango, Papaya, Kiwi, Pomegranate, Fig, Date, Passion fruit, Guava, Lychee, Dragon fruit, Starfruit, Persimmon, Cranberry, Gooseberry, Redcurrant, Blackcurrant, Whitecurrant, Elderberry, Mulberry, Boysenberry, Loganberry, Cloudberry, Kumquat, Tangerine, Clementine, Mandarin, Satsuma, Blood orange, Pomelo, Yuzu, Meyer lemon, Key lime, Plantain, Coconut, Avocado, Olive, Rhubarb, Quince, Medlar, Loquat, Rambutan, Mangosteen, Jackfruit, Durian, Breadfruit, Soursop, Cherimoya, Tamarillo, Horned melon, Gala apple, Granny Smith apple, Fuji apple, Honeycrisp apple, Pink Lady apple, Braeburn apple, Cox Orange Pippin, Bramley apple, Conference pear, Bartlett pear, Comice pear, Bosc pear, Concord grape, Sultana grape, Muscat grape, Thompson seedless grape, Crimson seedless grape, Navel orange, Valencia orange, Seville orange, White peach, Donut peach, Victoria plum, Damson, Greengage, Bing cherry, Rainier cherry, Morello cherry, Galia melon, Charentais melon.
Chicken breast, Chicken thigh, Chicken wing, Chicken drumstick, Whole chicken, Turkey breast, Ground turkey, Whole turkey, Duck breast, Whole duck, Goose, Quail, Pheasant, Guinea fowl, Beef mince, Beef sirloin steak, Beef ribeye steak, Beef fillet, Beef rump steak, Beef flank steak, Beef brisket, Beef chuck roast, Beef short ribs, Oxtail, Veal cutlet, Veal chop, Pork chop, Pork loin, Pork belly, Pork shoulder, Pork ribs, Pork mince, Bacon, Pancetta, Gammon, Ham, Lamb chop, Lamb leg, Lamb shoulder, Lamb shank, Lamb mince, Mutton, Venison steak, Venison sausage, Wild boar, Rabbit, Goat meat, Chicken liver, Beef liver, Calf liver, Lamb liver, Kidney, Heart, Tripe, Sweetbread, Bone marrow, Sausage pork, Sausage beef, Cumberland sausage, Lincolnshire sausage, Chorizo, Salami, Pepperoni, Prosciutto, Parma ham, Serrano ham, Pastrami, Corned beef, Salt beef, Black pudding, White pudding, Haggis, Frankfurters, Bratwurst, Kielbasa, Nduja, Mortadella, Bresaola, Coppa, Lardo, Guanciale, Meatballs, Burger patty, Chicken sausage, Turkey bacon, Duck fat, Beef tallow, Lard, Goose fat, Suet, Pulled pork, Rotisserie chicken, Diced chicken, Diced beef, Beef medallions, Lamb noisette, Pork tenderloin, Spatchcock chicken, Beef shin, Pork leg roast.
Salmon fillet, Smoked salmon, Cod fillet, Haddock, Tuna steak, Canned tuna, Trout, Sea bass, Sea bream, Mackerel, Smoked mackerel, Sardine, Anchovy, Herring, Kipper, Halibut, Turbot, Sole, Lemon sole, Plaice, Flounder, Monkfish, Swordfish, Mahi-mahi, Snapper, Grouper, Pollock, Coley, Hake, Whiting, Mullet, Tilapia, Pangasius, Carp, Pike, Catfish, Eel, Smoked eel, Sprat, Whitebait, King prawn, Cold water shrimp, Tiger prawn, Langoustine, Lobster, Crayfish, Brown crab, Spider crab, Soft-shell crab, Dressed crab, Scallop, Mussel, Oyster, Clam, Cockle, Whelk, Winkle, Calamari, Cuttlefish, Octopus, Caviar, Salmon roe, Lumpfish roe, Cod roe, Tarama, Sea urchin, Abalone, Razor clam, Geoduck, Crab stick, Fish cake, Fish finger, Scampi, Whitefish, Skate wing, Ray wing, Gurnard, John Dory, Brill, Megrim, Coalfish, Ling, Cusk, Marlin, Shark steak, Bluefish, Butterfish, Milkfish, Barramundi, Amberjack, Yellowtail, Pompano, Wahoo, Sea trout, Orange roughy, Prawn cracker, Dried shrimp, Bonito flakes, Seaweed.
Whole milk, Semi-skimmed milk, Skimmed milk, Evaporated milk, Condensed milk, Buttermilk, Double cream, Single cream, Whipping cream, Clotted cream, Sour cream, Creme fraiche, Salted butter, Unsalted butter, Ghee, Margarine, Natural yogurt, Greek yogurt, Flavored yogurt, Skyr, Kefir, Quark, Cottage cheese, Cream cheese, Mascarpone, Ricotta, Mozzarella, Burrata, Mild cheddar, Mature cheddar, Red Leicester, Double Gloucester, Cheshire cheese, Wensleydale, Stilton, Brie, Camembert, Roquefort, Gorgonzola, Parmesan, Grana Padano, Pecorino, Feta, Halloumi, Paneer, Gouda, Edam, Emmental, Gruyere, Comte, Manchego, Havarti, Provolone, Taleggio, Fontina, Monterey Jack, Pepper Jack, Swiss cheese, Blue cheese, Goats cheese, Sheep milk cheese, Processed cheese slices, Cheese spread, Babybel, Large egg, Medium egg, Quail egg, Duck egg, Goose egg, Soy milk, Almond milk, Oat milk, Coconut milk, Rice milk, Cashew milk, Macadamia milk, Hazelnut milk, Hemp milk, Pea milk, Vegan butter, Vegan cheese, Vegan yogurt, Silken tofu, Firm tofu, Tempeh, Seitan, Smetana, Velveeta, Whey protein, Casein protein, Egg whites, Custard, Rice pudding, Chocolate milk, Strawberry milk, Milk powder, Whey powder, Fromage frais, Aerosol cream, Cheese strings.
White bread, Wholemeal bread, Granary bread, Sourdough loaf, Baguette, Ciabatta, Focaccia, Pitta bread, Naan bread, Chapati, Tortilla wrap, Bagel, English muffin, Crumpet, Croissant, Pain au chocolat, Brioche, Hot cross bun, Teacake, Scone, Rye bread, Pumpernickel, Cornbread, Soda bread, Flatbread, Matzo, Crispbread, Rice cake, Oatcake, Grissini, Crouton, Breadcrumb, Panko, Pizza dough, Puff pastry, Shortcrust pastry, Filo pastry, Choux pastry, Sponge cake, Fruit cake, Brownie, Muffin, Cupcake, Doughnut, Danish pastry, Eclair, Tart, Pie, Quiche, Sausage roll, Cornish pasty, Rolled oat, Steel-cut oat, Porridge oat, Muesli, Granola, Corn flake, Bran flake, Rice crisp, Wheat biscuit, All-purpose flour, Self-raising flour, Whole wheat flour, Bread flour, Pasta flour, Almond flour, Coconut flour, Cornmeal, Polenta, Semolina, Gram flour, Spelt flour, Rye flour, Buckwheat flour, Tapioca starch, Potato starch, Cornstarch, Arrowroot, Long grain rice, Basmati rice, Jasmine rice, Brown rice, Arborio rice, Carnaroli rice, Sushi rice, Wild rice, Glutinous rice, Quinoa, Couscous, Bulgur wheat, Pearl barley, Farro, Freekeh, Millet, Amaranth, Sorghum, Teff, Spaghetti, Penne, Fusilli.
Extra virgin olive oil, Light olive oil, Sunflower oil, Vegetable oil, Rapeseed oil, Sesame oil, Coconut oil, Peanut oil, Avocado oil, Walnut oil, Truffle oil, White vinegar, Malt vinegar, Apple cider vinegar, Balsamic vinegar, Red wine vinegar, White wine vinegar, Rice vinegar, Light soy sauce, Dark soy sauce, Tamari, Teriyaki sauce, Hoisin sauce, Oyster sauce, Fish sauce, Sriracha, Sweet chili sauce, Tabasco sauce, Cholula, Worcester sauce, Brown sauce, Tomato ketchup, Mayonnaise, Salad cream, English mustard, Dijon mustard, Wholegrain mustard, Horseradish sauce, Tartare sauce, Mint sauce, Cranberry sauce, Apple sauce, Bread sauce, Gravy granules, Beef stock cube, Chicken stock cube, Vegetable stock cube, Fish stock cube, Yeast extract, Table salt, Sea salt, Whole black pepper, Ground black pepper, White pepper, Sweet paprika, Smoked paprika, Cayenne pepper, Chili powder, Chili flake, Ground cumin, Cumin seed, Ground coriander, Coriander seed, Turmeric, Cinnamon stick, Ground cinnamon, Nutmeg, Mace, Clove, Allspice, Green cardamom, Black cardamom, Star anise, Fennel seed, Mustard seed, Fenugreek, Saffron, Vanilla extract, Vanilla pod, Almond extract, Dried basil, Dried oregano, Dried thyme, Dried rosemary, Dried sage, Dried parsley, Dried mint, Dried tarragon, Dried dill, Bay leaf, Mixed herb, Herbes de Provence, Garam masala, Mild curry powder, Hot curry powder, Chinese five-spice, Ras el hanout, Zaatar, Sumac, Curry leaf.
Baked bean, Kidney bean, Cannellini bean, Butter bean, Borlotti bean, Black bean, Pinto bean, Haricot bean, Chickpea, Green lentil, Red lentil, Puy lentil, Split pea, Chopped tomato, Canned plum tomato, Tomato paste, Passata, Sun-dried tomato, Canned sweetcorn, Canned pea, Canned carrot, Canned mushroom, Artichoke heart, Green olive, Kalamata olive, Caper, Gherkin, Pickled onion, Pickled beetroot, Pickled cabbage, Sauerkraut, Kimchi, Jalapeno jar, Roasted red pepper, Anchovy tin, Sardine tin, Mackerel tin, Tuna tin, Salmon tin, Corned beef tin, Spam, Hot dog jar, Chicken soup, Tomato soup, Mushroom soup, Minestrone soup, Baked bean with sausage, Canned ravioli, Macaroni cheese, Coconut milk tin, Coconut cream tin, Evaporated milk tin, Condensed milk tin, Canned rice pudding, Canned custard, Peach half, Pear half, Pineapple ring, Fruit cocktail, Mandarin orange, Canned cherry, Strawberry jam, Raspberry jam, Apricot jam, Blackcurrant jam, Orange marmalade, Lemon curd, Clear honey, Set honey, Maple syrup, Golden syrup, Treacle, Molasses, Agave nectar, Smooth peanut butter, Crunchy peanut butter, Almond butter, Cashew butter, Hazelnut spread, Biscoff spread, Tahini, Green pesto, Red pesto, Tikka Masala paste, Korma paste, Madras paste, Thai green curry paste, Thai red curry paste, Tomato basil pasta sauce, Bolognese sauce, Bechamel sauce, Cheese sauce, Sweet and sour sauce, Black bean sauce, Mango chutney, Onion chutney, Piccalilli, Branston pickle, Chilli jam.
Salted potato crisp, Cheese and onion crisp, Salt and vinegar crisp, Tortilla chip, Pretzel, Sweet popcorn, Salted popcorn, Roasted salted peanut, Cashew nut, Almond, Walnut, Pecan, Hazelnut, Macadamia nut, Brazil nut, Pistachio, Pine nut, Sunflower seed, Pumpkin seed, Chia seed, Flaxseed, Sesame seed, Hemp seed, Raisin, Sultana, Currant, Dried apricot, Dried fig, Dried date, Dried cranberry, Dried mango, Prune, Milk chocolate bar, Dark chocolate bar, White chocolate bar, Chocolate truffle, Chocolate button, Gummy bear, Jelly baby, Wine gum, Licorice, Mint candy, Toffee, Fudge, Caramel, Marshmallow, Digestive biscuit, Rich Tea biscuit, Hobnob, Jaffa Cake, Bourbon biscuit, Custard Cream, Shortbread, Ginger nut, Chocolate chip cookie, Water biscuit, Cream cracker, Black tea bag, Earl Grey tea, Green tea, Peppermint tea, Chamomile tea, Fruit tea, Matcha powder, Instant coffee, Ground coffee, Coffee bean, Coffee pod, Hot chocolate powder, Cocoa powder, Horlicks, Cola, Diet Cola, Lemonade, Orange soda, Ginger ale, Ginger beer, Tonic water, Soda water, Sparkling mineral water, Still mineral water, Orange juice, Apple juice, Cranberry juice, Pineapple juice, Tomato juice, Grapefruit juice, Pomegranate juice, Orange squash, Blackcurrant squash, Elderflower cordial, Energy drink, Sports drink, Lager, Ale, Stout, Cider, Red wine, White wine, Prosecco.
Frozen pea, Frozen sweetcorn, Frozen mixed vegetable, Frozen spinach, Frozen broccoli, Frozen cauliflower, Frozen edamame, Frozen chip, Frozen potato wedge, Frozen hash brown, Frozen roast potato, Frozen onion ring, Margherita pizza, Pepperoni pizza, Frozen garlic bread, Frozen fish finger, Frozen battered cod, Frozen breaded scampi, Frozen prawn, Frozen chicken nugget, Frozen chicken dipper, Frozen chicken kiev, Frozen beef burger, Frozen veggie burger, Frozen sausage, Frozen meat pie, Frozen pasty, Frozen Yorkshire pudding, Curry ready meal, Pasta ready meal, Sweet and sour ready meal, Frozen dumpling, Frozen spring roll, Frozen samosa, Frozen falafel, Frozen puff pastry, Frozen shortcrust pastry, Frozen berry mix, Frozen strawberry, Frozen raspberry, Frozen blueberry, Frozen mango chunk, Vanilla ice cream, Chocolate ice cream, Strawberry ice cream, Mint choc chip ice cream, Neapolitan ice cream, Cookie dough ice cream, Lemon sorbet, Raspberry sorbet, Gelato, Ice lolly, Ice cream cone, Ice cream sandwich, Frozen yogurt, Frozen cheesecake, Frozen gateau, Frozen profiterole, Frozen eclair, Ice cube, Granulated sugar, Caster sugar, Icing sugar, Light brown sugar, Dark brown sugar, Muscovado sugar, Demerara sugar, Baking powder, Bicarbonate of soda, Dried yeast, Fresh yeast, Cocoa butter, Chocolate chip, Desiccated coconut, Flaked almond, Ground almond, Marzipan, Fondant icing, Food coloring, Sprinkles, Vermicelli noodles, Udon noodles, Soba noodles, Egg noodles, Rice noodles, Ramen noodles, Gnocchi, Tortellini, Fresh ravioli, Macaroni, Orzo, Lasagne sheet, Cannelloni tube, Polenta, Taco shell, Enchilada kit, Fajita kit, Poppadom, Prawn cracker.
"""

var seen = Set<String>()
var items: [String] = []
for part in RAW.split(whereSeparator: { $0 == "," || $0 == "\n" || $0 == "." }) {
    let t = part.trimmingCharacters(in: .whitespacesAndNewlines)
    let key = t.lowercased()
    if t.count > 1, seen.insert(key).inserted { items.append(t) }
}

var curated = 0, semantic = 0, fallbackItems: [String] = []
var semanticSamples: [(String, String)] = []
for item in items {
    if EmojiTable.match(item) != nil {
        curated += 1
    } else if let s = SemanticEmoji.match(item) {
        semantic += 1
        if semanticSamples.count < 60 { semanticSamples.append((item, s)) }
    } else {
        fallbackItems.append(item)
    }
}

print("Items (unique): \(items.count)")
print("  curated:  \(curated)")
print("  semantic: \(semantic)")
print("  fallback: \(fallbackItems.count)")
print("\n-- resolved by SEMANTIC embedding (sample) --")
for (i, e) in semanticSamples { print("  \(e)  \(i)") }
print("\n-- fell through to basket (gaps) --")
print(fallbackItems.isEmpty ? "  (none)" : fallbackItems.map { "  \($0)" }.joined(separator: "\n"))
