#!/usr/bin/env python3
"""Generates Sources/Services/SuggestionDictionary.swift — the vocabulary that
powers typing autocomplete (alongside the user's personal history).

Unifies three sources so anything the app understands can also be suggested:
  1. The mainstream grocery corpus (curated, nicely cased) — wins on casing.
  2. Every regional corpus (african, east_asian, european, latam_caribbean,
     mena, south_asian, southeast_asian), with parenthetical glosses stripped
     ("gai lan (Chinese broccoli)" -> "Gai lan").
  3. The emoji table's keyword vocabulary, so emoji-known items can be typed
     ahead too (e.g. "cordial" -> 🧃 was missing from suggestions before),
     minus a handful of truncated stems ("strawberr", "anchov", …) used only
     for prefix matching.

Dedupe is case-insensitive, first source wins. Output is sorted alphabetically
so regenerated diffs stay stable and reviewable; Suggestions re-ranks anyway."""
import os, re, sys, glob

HERE = os.path.dirname(__file__)
CORPUS = os.path.join(HERE, "corpus")
EMOJI_TABLE = os.path.join(HERE, "..", "Sources", "Services", "EmojiTable.swift")


def nice(raw):
    """Trim, drop a trailing period, strip any "(gloss)", and uppercase only the
    first letter — matching the app's own `capitalisedFirstLetter` casing, so a
    curated "Tomato Soup" is preserved while a lowercase "gai lan" becomes
    "Gai lan"."""
    s = re.sub(r"\s*\([^)]*\)", "", raw.strip().rstrip(".")).strip()
    s = re.sub(r"\s{2,}", " ", s)
    return (s[:1].upper() + s[1:]) if s else ""


seen, names = set(), []


def add(raw):
    n = nice(raw)
    if not n:
        return
    k = n.lower()
    if k not in seen:
        seen.add(k)
        names.append(n)


# 1) grocery corpus first, so its curated casing wins any collision.
with open(os.path.join(CORPUS, "grocery_corpus.txt"), encoding="utf-8") as f:
    for line in f:
        add(line)

# 2) regional corpora, in a fixed (alphabetical) order for stable output.
for path in sorted(glob.glob(os.path.join(CORPUS, "*.txt"))):
    if os.path.basename(path) == "grocery_corpus.txt":
        continue
    with open(path, encoding="utf-8") as f:
        for line in f:
            add(line)


# 3) emoji-table keyword vocabulary. A few entries are truncated stems used only
# for prefix matching ("strawberr", the *berr family, "anchov", "pastr",
# "cherr") — skip those so we never suggest a fragment; their real spellings
# already arrive from the corpora above.
def is_stem(kw):
    return kw.endswith("berr") or kw in {"cherr", "anchov", "pastr"}


with open(EMOJI_TABLE, encoding="utf-8") as f:
    for kw, _glyph in re.findall(r'\("([^"]+)",\s*"([^"]+)"\)', f.read()):
        kw = kw.strip()
        if kw and not is_stem(kw.lower()):
            add(kw)

names.sort(key=str.lower)

body = ",\n".join('        "%s"' % n.replace("\\", "\\\\").replace('"', '\\"') for n in names)
swift = '''import Foundation

// GENERATED by tools/gen_suggestions.py — do not hand-edit; edit the sources
// (corpus/*.txt and the emoji table's keywords) and re-run the generator.
// Common item names for typing autocomplete, merged with the user's personal
// history in Suggestions. Unifies the grocery + regional corpora with the emoji
// table's vocabulary, so anything the app can emoji it can also suggest.
enum SuggestionDictionary {
    static let items: [String] = [
%s,
    ]
}
''' % body

out = sys.argv[1] if len(sys.argv) > 1 else "Sources/Services/SuggestionDictionary.swift"
with open(out, "w", encoding="utf-8") as f:
    f.write(swift)
print(f"wrote {out} with {len(names)} names")
