#!/usr/bin/env python3
"""Generates Sources/Services/SuggestionDictionary.swift from the mainstream
grocery corpus — a clean list of common, nicely-cased item names used to power
typing autocomplete (alongside the user's personal history)."""
import os, sys

src = os.path.join(os.path.dirname(__file__), "corpus", "grocery_corpus.txt")
seen, names = set(), []
with open(src) as f:
    for line in f:
        n = line.strip().rstrip(".")
        # skip anything with a parenthetical gloss to keep suggestions clean
        if not n or "(" in n:
            continue
        k = n.lower()
        if k not in seen:
            seen.add(k)
            names.append(n)

lines = ",\n".join(f'        "{n}"' for n in names)
swift = '''import Foundation

// GENERATED by tools/gen_suggestions.py — common grocery names for typing
// autocomplete (merged with the user's personal history in Suggestions).
enum SuggestionDictionary {
    static let items: [String] = [
%s,
    ]
}
''' % lines

out = sys.argv[1] if len(sys.argv) > 1 else "Sources/Services/SuggestionDictionary.swift"
with open(out, "w") as f:
    f.write(swift)
print(f"wrote {out} with {len(names)} names")
