#!/usr/bin/env python3
"""Generates Sources/Services/MeasureTable.swift — a curated keyword->measure
type table that picks a sensible default unit for an item (count / weight /
volume). Mirrors the emoji table's structure (tools/gen_emoji.py): "complex"
keywords (with a space/hyphen) match as substrings first, then single words
match by word-prefix.

Only VOLUME and WEIGHT keywords are listed — anything unmatched defaults to
COUNT (the least-surprising default; the user can change the unit anyway). The
Swift matcher checks volume keywords before weight ones, so "almond milk" lands
on volume (via "milk") rather than weight (via "almond"). A few multi-word
overrides (e.g. "cream cheese" -> weight) are listed as complex keywords so they
win over the single-word sweep."""
import re, sys

RAW = r"""
# --- VOLUME: things you pour (liquids). "milk" covers "almond milk", "oil"
#     covers "olive oil", etc., and volume wins over weight in the matcher. ---
("milk", "volume"),("cream", "volume"),("juice", "volume"),("oil", "volume"),
("vinegar", "volume"),("water", "volume"),("soda", "volume"),("cola", "volume"),
("lemonade", "volume"),("tonic", "volume"),("cordial", "volume"),("squash drink", "volume"),
("wine", "volume"),("beer", "volume"),("lager", "volume"),("ale", "volume"),("cider", "volume"),
("stout", "volume"),("prosecco", "volume"),("champagne", "volume"),("vodka", "volume"),
("gin", "volume"),("whisky", "volume"),("whiskey", "volume"),("rum", "volume"),("brandy", "volume"),
("tequila", "volume"),("liqueur", "volume"),("stock", "volume"),("broth", "volume"),
("smoothie", "volume"),("milkshake", "volume"),("kombucha", "volume"),("syrup", "volume"),
("squash", "volume"),
# --- WEIGHT: things you weigh (loose, bulk, dry goods, meat, fish, cheese). ---
("beef", "weight"),("steak", "weight"),("mince", "weight"),("lamb", "weight"),("pork", "weight"),
("chicken", "weight"),("turkey", "weight"),("duck", "weight"),("sausage", "weight"),("bacon", "weight"),
("ham", "weight"),("gammon", "weight"),("meat", "weight"),("veal", "weight"),("venison", "weight"),
("salmon", "weight"),("cod", "weight"),("haddock", "weight"),("tuna", "weight"),("mackerel", "weight"),
("sardine", "weight"),("prawn", "weight"),("shrimp", "weight"),("fish", "weight"),("fillet", "weight"),
("cheese", "weight"),("cheddar", "weight"),("mozzarella", "weight"),("parmesan", "weight"),
("feta", "weight"),("halloumi", "weight"),("gouda", "weight"),("brie", "weight"),("paneer", "weight"),
("flour", "weight"),("sugar", "weight"),("rice", "weight"),("pasta", "weight"),("spaghetti", "weight"),
("oats", "weight"),("oat", "weight"),("quinoa", "weight"),("couscous", "weight"),("lentil", "weight"),
("bean", "weight"),("chickpea", "weight"),("nut", "weight"),("almond", "weight"),("cashew", "weight"),
("walnut", "weight"),("peanut", "weight"),("raisin", "weight"),("sultana", "weight"),("salt", "weight"),
("butter", "weight"),("mushroom", "weight"),("potato", "weight"),("carrot", "weight"),("onion", "weight"),
("tomato", "weight"),("broccoli", "weight"),("cauliflower", "weight"),("cabbage", "weight"),
("spinach", "weight"),("kale", "weight"),("courgette", "weight"),("aubergine", "weight"),
("grape", "weight"),("cherry", "weight"),("strawberries", "weight"),("blueberries", "weight"),
("raspberries", "weight"),("mince", "weight"),("flour", "weight"),
# --- multi-word overrides (checked first; correct the single-word sweep) ---
("cream cheese", "weight"),("water chestnut", "weight"),("peanut butter", "weight"),
("ice cream", "count"),
"""

pairs = re.findall(r'\("([^"]+)",\s*"([^"]+)"\)', RAW)
seen, table = set(), []
for kw, t in pairs:
    kw = kw.strip().lower()
    if kw in seen:
        continue
    seen.add(kw)
    table.append((kw, t))

lines = ",\n".join(f'        ("{kw}", .{t})' for kw, t in table)
swift = '''import Foundation

// GENERATED by tools/gen_measure.py — do not hand-edit; edit the data there and re-run.
// Curated keyword->measure-type table (~%d entries). Only volume/weight are
// listed; anything unmatched defaults to .count (see Measure.typeForName).
// Mirrors EmojiTable: "complex" keywords (with a space/hyphen) match as
// substrings first, then single words match by word-prefix. Volume is checked
// before weight so e.g. "almond milk" → .volume (via "milk"), not .weight.
enum MeasureTable {
    static let entries: [(String, MeasureType)] = [
%s,
    ]

    private static let complexKeywords: [(String, MeasureType)] =
        entries.filter { $0.0.contains { !$0.isLetter } }
               .sorted { $0.0.count > $1.0.count }
    private static let simpleVolume: [(String, MeasureType)] =
        entries.filter { !$0.0.contains { !$0.isLetter } && $0.1 == .volume }
               .sorted { $0.0.count > $1.0.count }
    private static let simpleWeight: [(String, MeasureType)] =
        entries.filter { !$0.0.contains { !$0.isLetter } && $0.1 == .weight }
               .sorted { $0.0.count > $1.0.count }

    /// Curated measure type, or nil if nothing applies (caller defaults to .count).
    static func match(_ name: String) -> MeasureType? {
        let lower = name.lowercased()
        for (keyword, type) in complexKeywords where lower.contains(keyword) {
            return type
        }
        let words = lower.split { !$0.isLetter }.map(String.init)
        for (keyword, type) in simpleVolume
        where words.contains(where: { $0.hasPrefix(keyword) }) {
            return type
        }
        for (keyword, type) in simpleWeight
        where words.contains(where: { $0.hasPrefix(keyword) }) {
            return type
        }
        return nil
    }
}
''' % (len(table), lines)

out = sys.argv[1] if len(sys.argv) > 1 else "Sources/Services/MeasureTable.swift"
with open(out, "w", encoding="utf-8") as f:
    f.write(swift)
print(f"wrote {out} with {len(table)} entries")
